version: '3.7'
services:
  db:
    volumes:
      - ".:/app"
      - "./setup/setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro"
    image: mysql
    container_name: checkout-server-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
